---
- name: Install k3s on EC2 instance
  hosts: all
  become: yes
  tasks:
    - name: Create a 2GB swap file
      command: fallocate -l 2G /swapfile
      args:
        creates: /swapfile

    - name: Set swap file permissions
      file:
        path: /swapfile
        mode: '0600'

    - name: Format the swap file
      command: mkswap /swapfile
      when: not ansible_swaptotal_mb > 0

    - name: Enable the swap file
      command: swapon /swapfile
      when: not ansible_swaptotal_mb > 0

    - name: Add swap to fstab
      mount:
        name: none
        src: /swapfile
        fstype: swap
        opts: sw
        passno: '0'
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Download k3s installation script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/install_k3s.sh
        mode: '0755'

    - name: Install k3s
      command: sh /tmp/install_k3s.sh
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for k3s node to be ready
      command: k3s kubectl get nodes
      register: nodes_output
      until: "' Ready ' in nodes_output.stdout"
      retries: 5
      delay: 10

    - name: Change permissions of k3s config for ubuntu user
      file:
        path: /etc/rancher/k3s/k3s.yaml
        mode: '0644'
